### ISSUE TITLE
ui-select非multiple模式下使用tagging

### ISSUE THREAD

**Issue by knwei** [yqfang/UForm#14]
业务场景：提供可选择、可录入的并可以翻译取值的控件，使用了ui-select，但是发现在multiple模式下，tagging有效，但在非multiple模式下，tagging无效，请确认，如可以，可否给出例子。

**Comment by yqfang** [comment]
demo 已经更新， 请更新到最新的 up-lib
1. 修复了 ui-select 非 multiple 模式下 enter 无效的bug

**Comment by knwei** [comment]
使用 ng-init="vm.init(vm.field.model, vm.form.result[vm.field.name])"初始化值

this.init = function(options, value) {
					value = '小明11';
					if (value && value != "") {
						vm.result = {};
						for (var i=0; i<options.length; i++) {
							if (options[i].name == value) {
								vm.result["name"] = options[i].name;
								vm.result["email"] = options[i].email;
								break ;
							}
						}
						
						if (!vm.result["name"]) {
//
						}
					}
				};

发现如果值在列表里，则显示没问题，如果值不在列表里，就不显示了，这个可以解决吗？
